// Auto-generated. Do not edit!

// (in-package planner.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class ComputeTrajectoryGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.InputPoint = null;
      this.InitLabel = null;
    }
    else {
      if (initObj.hasOwnProperty('InputPoint')) {
        this.InputPoint = initObj.InputPoint
      }
      else {
        this.InputPoint = new geometry_msgs.msg.PoseArray();
      }
      if (initObj.hasOwnProperty('InitLabel')) {
        this.InitLabel = initObj.InitLabel
      }
      else {
        this.InitLabel = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ComputeTrajectoryGoal
    // Serialize message field [InputPoint]
    bufferOffset = geometry_msgs.msg.PoseArray.serialize(obj.InputPoint, buffer, bufferOffset);
    // Serialize message field [InitLabel]
    bufferOffset = _arraySerializer.string(obj.InitLabel, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ComputeTrajectoryGoal
    let len;
    let data = new ComputeTrajectoryGoal(null);
    // Deserialize message field [InputPoint]
    data.InputPoint = geometry_msgs.msg.PoseArray.deserialize(buffer, bufferOffset);
    // Deserialize message field [InitLabel]
    data.InitLabel = _arrayDeserializer.string(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PoseArray.getMessageSize(object.InputPoint);
    object.InitLabel.forEach((val) => {
      length += 4 + val.length;
    });
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'planner/ComputeTrajectoryGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e134294baa46c81d09a022be523a4827';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    geometry_msgs/PoseArray InputPoint
    string[] InitLabel
    
    ================================================================================
    MSG: geometry_msgs/PoseArray
    # An array of poses with a header for global reference.
    
    Header header
    
    Pose[] poses
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ComputeTrajectoryGoal(null);
    if (msg.InputPoint !== undefined) {
      resolved.InputPoint = geometry_msgs.msg.PoseArray.Resolve(msg.InputPoint)
    }
    else {
      resolved.InputPoint = new geometry_msgs.msg.PoseArray()
    }

    if (msg.InitLabel !== undefined) {
      resolved.InitLabel = msg.InitLabel;
    }
    else {
      resolved.InitLabel = []
    }

    return resolved;
    }
};

module.exports = ComputeTrajectoryGoal;
