// Generated by gencpp from file planner/ComputeTrajectoryResult.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_COMPUTETRAJECTORYRESULT_H
#define PLANNER_MESSAGE_COMPUTETRAJECTORYRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace planner
{
template <class ContainerAllocator>
struct ComputeTrajectoryResult_
{
  typedef ComputeTrajectoryResult_<ContainerAllocator> Type;

  ComputeTrajectoryResult_()
    : FinalTrajectories()
    , FinalLabel()  {
    }
  ComputeTrajectoryResult_(const ContainerAllocator& _alloc)
    : FinalTrajectories(_alloc)
    , FinalLabel(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseArray_<ContainerAllocator> >::other >  _FinalTrajectories_type;
  _FinalTrajectories_type FinalTrajectories;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _FinalLabel_type;
  _FinalLabel_type FinalLabel;





  typedef boost::shared_ptr< ::planner::ComputeTrajectoryResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::ComputeTrajectoryResult_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeTrajectoryResult_

typedef ::planner::ComputeTrajectoryResult_<std::allocator<void> > ComputeTrajectoryResult;

typedef boost::shared_ptr< ::planner::ComputeTrajectoryResult > ComputeTrajectoryResultPtr;
typedef boost::shared_ptr< ::planner::ComputeTrajectoryResult const> ComputeTrajectoryResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::ComputeTrajectoryResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::ComputeTrajectoryResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner::ComputeTrajectoryResult_<ContainerAllocator1> & lhs, const ::planner::ComputeTrajectoryResult_<ContainerAllocator2> & rhs)
{
  return lhs.FinalTrajectories == rhs.FinalTrajectories &&
    lhs.FinalLabel == rhs.FinalLabel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner::ComputeTrajectoryResult_<ContainerAllocator1> & lhs, const ::planner::ComputeTrajectoryResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner::ComputeTrajectoryResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::ComputeTrajectoryResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::ComputeTrajectoryResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::ComputeTrajectoryResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::ComputeTrajectoryResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::ComputeTrajectoryResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::ComputeTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40834ff98d5d7863bdb61af7ff11587a";
  }

  static const char* value(const ::planner::ComputeTrajectoryResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40834ff98d5d7863ULL;
  static const uint64_t static_value2 = 0xbdb61af7ff11587aULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::ComputeTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/ComputeTrajectoryResult";
  }

  static const char* value(const ::planner::ComputeTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::ComputeTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"geometry_msgs/PoseArray[] FinalTrajectories\n"
"string[] FinalLabel\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::planner::ComputeTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::ComputeTrajectoryResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FinalTrajectories);
      stream.next(m.FinalLabel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeTrajectoryResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::ComputeTrajectoryResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::ComputeTrajectoryResult_<ContainerAllocator>& v)
  {
    s << indent << "FinalTrajectories[]" << std::endl;
    for (size_t i = 0; i < v.FinalTrajectories.size(); ++i)
    {
      s << indent << "  FinalTrajectories[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "    ", v.FinalTrajectories[i]);
    }
    s << indent << "FinalLabel[]" << std::endl;
    for (size_t i = 0; i < v.FinalLabel.size(); ++i)
    {
      s << indent << "  FinalLabel[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.FinalLabel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_COMPUTETRAJECTORYRESULT_H
