// Generated by gencpp from file planner/ComputeTrajectoryGoal.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_COMPUTETRAJECTORYGOAL_H
#define PLANNER_MESSAGE_COMPUTETRAJECTORYGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace planner
{
template <class ContainerAllocator>
struct ComputeTrajectoryGoal_
{
  typedef ComputeTrajectoryGoal_<ContainerAllocator> Type;

  ComputeTrajectoryGoal_()
    : InputPoint()
    , InitLabel()  {
    }
  ComputeTrajectoryGoal_(const ContainerAllocator& _alloc)
    : InputPoint(_alloc)
    , InitLabel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _InputPoint_type;
  _InputPoint_type InputPoint;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _InitLabel_type;
  _InitLabel_type InitLabel;





  typedef boost::shared_ptr< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeTrajectoryGoal_

typedef ::planner::ComputeTrajectoryGoal_<std::allocator<void> > ComputeTrajectoryGoal;

typedef boost::shared_ptr< ::planner::ComputeTrajectoryGoal > ComputeTrajectoryGoalPtr;
typedef boost::shared_ptr< ::planner::ComputeTrajectoryGoal const> ComputeTrajectoryGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::ComputeTrajectoryGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner::ComputeTrajectoryGoal_<ContainerAllocator1> & lhs, const ::planner::ComputeTrajectoryGoal_<ContainerAllocator2> & rhs)
{
  return lhs.InputPoint == rhs.InputPoint &&
    lhs.InitLabel == rhs.InitLabel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner::ComputeTrajectoryGoal_<ContainerAllocator1> & lhs, const ::planner::ComputeTrajectoryGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e134294baa46c81d09a022be523a4827";
  }

  static const char* value(const ::planner::ComputeTrajectoryGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe134294baa46c81dULL;
  static const uint64_t static_value2 = 0x09a022be523a4827ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/ComputeTrajectoryGoal";
  }

  static const char* value(const ::planner::ComputeTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
"geometry_msgs/PoseArray InputPoint\n"
"string[] InitLabel\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::planner::ComputeTrajectoryGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.InputPoint);
      stream.next(m.InitLabel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeTrajectoryGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::ComputeTrajectoryGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::ComputeTrajectoryGoal_<ContainerAllocator>& v)
  {
    s << indent << "InputPoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.InputPoint);
    s << indent << "InitLabel[]" << std::endl;
    for (size_t i = 0; i < v.InitLabel.size(); ++i)
    {
      s << indent << "  InitLabel[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.InitLabel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_COMPUTETRAJECTORYGOAL_H
