// Generated by gencpp from file planner/ComputeTrajectoryFeedback.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_COMPUTETRAJECTORYFEEDBACK_H
#define PLANNER_MESSAGE_COMPUTETRAJECTORYFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner
{
template <class ContainerAllocator>
struct ComputeTrajectoryFeedback_
{
  typedef ComputeTrajectoryFeedback_<ContainerAllocator> Type;

  ComputeTrajectoryFeedback_()
    : output()  {
    }
  ComputeTrajectoryFeedback_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeTrajectoryFeedback_

typedef ::planner::ComputeTrajectoryFeedback_<std::allocator<void> > ComputeTrajectoryFeedback;

typedef boost::shared_ptr< ::planner::ComputeTrajectoryFeedback > ComputeTrajectoryFeedbackPtr;
typedef boost::shared_ptr< ::planner::ComputeTrajectoryFeedback const> ComputeTrajectoryFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner::ComputeTrajectoryFeedback_<ContainerAllocator1> & lhs, const ::planner::ComputeTrajectoryFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner::ComputeTrajectoryFeedback_<ContainerAllocator1> & lhs, const ::planner::ComputeTrajectoryFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const ::planner::ComputeTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0825d95fdfa2c8f4ULL;
  static const uint64_t static_value2 = 0xbbb4e9c74bccd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/ComputeTrajectoryFeedback";
  }

  static const char* value(const ::planner::ComputeTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"string output\n"
;
  }

  static const char* value(const ::planner::ComputeTrajectoryFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeTrajectoryFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::ComputeTrajectoryFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::ComputeTrajectoryFeedback_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_COMPUTETRAJECTORYFEEDBACK_H
