// Generated by gencpp from file schunk_pg70/reference.msg
// DO NOT EDIT!


#ifndef SCHUNK_PG70_MESSAGE_REFERENCE_H
#define SCHUNK_PG70_MESSAGE_REFERENCE_H

#include <ros/service_traits.h>


#include <schunk_pg70/referenceRequest.h>
#include <schunk_pg70/referenceResponse.h>


namespace schunk_pg70
{

struct reference
{

typedef referenceRequest Request;
typedef referenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reference
} // namespace schunk_pg70


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::schunk_pg70::reference > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::schunk_pg70::reference&) { return value(); }
};

template<>
struct DataType< ::schunk_pg70::reference > {
  static const char* value()
  {
    return "schunk_pg70/reference";
  }

  static const char* value(const ::schunk_pg70::reference&) { return value(); }
};


// service_traits::MD5Sum< ::schunk_pg70::referenceRequest> should match
// service_traits::MD5Sum< ::schunk_pg70::reference >
template<>
struct MD5Sum< ::schunk_pg70::referenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_pg70::reference >::value();
  }
  static const char* value(const ::schunk_pg70::referenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_pg70::referenceRequest> should match
// service_traits::DataType< ::schunk_pg70::reference >
template<>
struct DataType< ::schunk_pg70::referenceRequest>
{
  static const char* value()
  {
    return DataType< ::schunk_pg70::reference >::value();
  }
  static const char* value(const ::schunk_pg70::referenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::schunk_pg70::referenceResponse> should match
// service_traits::MD5Sum< ::schunk_pg70::reference >
template<>
struct MD5Sum< ::schunk_pg70::referenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::schunk_pg70::reference >::value();
  }
  static const char* value(const ::schunk_pg70::referenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::schunk_pg70::referenceResponse> should match
// service_traits::DataType< ::schunk_pg70::reference >
template<>
struct DataType< ::schunk_pg70::referenceResponse>
{
  static const char* value()
  {
    return DataType< ::schunk_pg70::reference >::value();
  }
  static const char* value(const ::schunk_pg70::referenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHUNK_PG70_MESSAGE_REFERENCE_H
