(cl:defpackage planner-msg
  (:use )
  (:export
   "<COMPUTETRAJECTORYACTION>"
   "COMPUTETRAJECTORYACTION"
   "<COMPUTETRAJECTORYACTIONFEEDBACK>"
   "COMPUTETRAJECTORYACTIONFEEDBACK"
   "<COMPUTETRAJECTORYACTIONGOAL>"
   "COMPUTETRAJECTORYACTIONGOAL"
   "<COMPUTETRAJECTORYACTIONRESULT>"
   "COMPUTETRAJECTORYACTIONRESULT"
   "<COMPUTETRAJECTORYFEEDBACK>"
   "COMPUTETRAJECTORYFEEDBACK"
   "<COMPUTETRAJECTORYGOAL>"
   "COMPUTETRAJECTORYGOAL"
   "<COMPUTETRAJECTORYRESULT>"
   "COMPUTETRAJECTORYRESULT"
  ))

