; Auto-generated. Do not edit!


(cl:in-package planner-msg)


;//! \htmlinclude ComputeTrajectoryGoal.msg.html

(cl:defclass <ComputeTrajectoryGoal> (roslisp-msg-protocol:ros-message)
  ((InputPoint
    :reader InputPoint
    :initarg :InputPoint
    :type geometry_msgs-msg:PoseArray
    :initform (cl:make-instance 'geometry_msgs-msg:PoseArray))
   (InitLabel
    :reader InitLabel
    :initarg :InitLabel
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass ComputeTrajectoryGoal (<ComputeTrajectoryGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ComputeTrajectoryGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ComputeTrajectoryGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name planner-msg:<ComputeTrajectoryGoal> is deprecated: use planner-msg:ComputeTrajectoryGoal instead.")))

(cl:ensure-generic-function 'InputPoint-val :lambda-list '(m))
(cl:defmethod InputPoint-val ((m <ComputeTrajectoryGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader planner-msg:InputPoint-val is deprecated.  Use planner-msg:InputPoint instead.")
  (InputPoint m))

(cl:ensure-generic-function 'InitLabel-val :lambda-list '(m))
(cl:defmethod InitLabel-val ((m <ComputeTrajectoryGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader planner-msg:InitLabel-val is deprecated.  Use planner-msg:InitLabel instead.")
  (InitLabel m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ComputeTrajectoryGoal>) ostream)
  "Serializes a message object of type '<ComputeTrajectoryGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'InputPoint) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'InitLabel))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'InitLabel))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ComputeTrajectoryGoal>) istream)
  "Deserializes a message object of type '<ComputeTrajectoryGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'InputPoint) istream)
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'InitLabel) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'InitLabel)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ComputeTrajectoryGoal>)))
  "Returns string type for a message object of type '<ComputeTrajectoryGoal>"
  "planner/ComputeTrajectoryGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ComputeTrajectoryGoal)))
  "Returns string type for a message object of type 'ComputeTrajectoryGoal"
  "planner/ComputeTrajectoryGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ComputeTrajectoryGoal>)))
  "Returns md5sum for a message object of type '<ComputeTrajectoryGoal>"
  "e134294baa46c81d09a022be523a4827")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ComputeTrajectoryGoal)))
  "Returns md5sum for a message object of type 'ComputeTrajectoryGoal"
  "e134294baa46c81d09a022be523a4827")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ComputeTrajectoryGoal>)))
  "Returns full string definition for message of type '<ComputeTrajectoryGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%geometry_msgs/PoseArray InputPoint~%string[] InitLabel~%~%================================================================================~%MSG: geometry_msgs/PoseArray~%# An array of poses with a header for global reference.~%~%Header header~%~%Pose[] poses~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ComputeTrajectoryGoal)))
  "Returns full string definition for message of type 'ComputeTrajectoryGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%geometry_msgs/PoseArray InputPoint~%string[] InitLabel~%~%================================================================================~%MSG: geometry_msgs/PoseArray~%# An array of poses with a header for global reference.~%~%Header header~%~%Pose[] poses~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ComputeTrajectoryGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'InputPoint))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'InitLabel) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ComputeTrajectoryGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ComputeTrajectoryGoal
    (cl:cons ':InputPoint (InputPoint msg))
    (cl:cons ':InitLabel (InitLabel msg))
))
