# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gripper_control/ControlOutput.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ControlOutput(genpy.Message):
  _md5sum = "3d113725e502b53b0e53b00acafaa65f"
  _type = "gripper_control/ControlOutput"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 output
float64 output_sat
float64 gripper_position
float64 error
float64 reference
float64 lower_bound
float64 upper_bound
float64 actual_value
"""
  __slots__ = ['output','output_sat','gripper_position','error','reference','lower_bound','upper_bound','actual_value']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       output,output_sat,gripper_position,error,reference,lower_bound,upper_bound,actual_value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControlOutput, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.output is None:
        self.output = 0.
      if self.output_sat is None:
        self.output_sat = 0.
      if self.gripper_position is None:
        self.gripper_position = 0.
      if self.error is None:
        self.error = 0.
      if self.reference is None:
        self.reference = 0.
      if self.lower_bound is None:
        self.lower_bound = 0.
      if self.upper_bound is None:
        self.upper_bound = 0.
      if self.actual_value is None:
        self.actual_value = 0.
    else:
      self.output = 0.
      self.output_sat = 0.
      self.gripper_position = 0.
      self.error = 0.
      self.reference = 0.
      self.lower_bound = 0.
      self.upper_bound = 0.
      self.actual_value = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.output, _x.output_sat, _x.gripper_position, _x.error, _x.reference, _x.lower_bound, _x.upper_bound, _x.actual_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.output, _x.output_sat, _x.gripper_position, _x.error, _x.reference, _x.lower_bound, _x.upper_bound, _x.actual_value,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.output, _x.output_sat, _x.gripper_position, _x.error, _x.reference, _x.lower_bound, _x.upper_bound, _x.actual_value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.output, _x.output_sat, _x.gripper_position, _x.error, _x.reference, _x.lower_bound, _x.upper_bound, _x.actual_value,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
